name: CI

on:
  push:
    branches:
      - main
  pull_request:
    # run CI only if files in these whitelisted paths are changed
    paths:
      - '.github/workflows/**'
      - 'rdmo_plugins_statistics/**'
      - 'tests/**'
      - .pre-commit-config.yaml
      - pyproject.toml
      - README.md

# Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONDONTWRITEBYTECODE: 1
  FORCE_COLOR: 1 # colored output by pytest etc.
  CLICOLOR_FORCE: 1 # colored output by ruff

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: pip
    - run: python -m pip install --upgrade pip setuptools wheel
    - run: python -m pip install -e .[dev]
    - name: Set up pre-commit cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: lint-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run linters via pre-commit (ruff, eslint)
      run: pre-commit run --all-files --color=always

  dev-setup:
    # Ref: structlog (MIT licensed) <https://github.com/hynek/structlog/blob/main/.github/workflows/ci.yml>
    name: "Test dev setup on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
      - run: python -Im pip install -e .[dev]
      - run: python -Ic 'import rdmo_plugins_statistics; print(rdmo_plugins_statistics.__version__)'

  test:
    name: "Test (${{ matrix.name }})"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: RDMO 2.5
            rdmo: "rdmo>=2.5,<3"
          - name: RDMO 3.0 release branch
            rdmo: "rdmo @ git+https://github.com/rdmorganiser/rdmo.git@3.0.0/release"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
      - run: python -m pip install --upgrade pip setuptools wheel
      - name: Install RDMO target
        run: python -m pip install "${{ matrix.rdmo }}"
      - name: Install plugin
        run: python -m pip install -e '.[dev]'
      - name: Run tests
        run: pytest

  required-checks-pass:
    if: always()
    needs:
      - lint
      - dev-setup
      - test
    runs-on: ubuntu-22.04
    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
